set_pheater_duration:
  description: "Set duration for parking heater/ventilation"
  fields:
    vin:
      description: "VIN number for vehicle to control. [VIN-number] str (required)"
      example: "ABCDE9FG0H1234567"
    duration:
      description: "[10,20,30,40,50,60] Parking heater duration for heating/ventilation"
      example: '20'
set_schedule:
  description: "Set a timer schedule"
  fields:
    vin:
      description: "VIN number for vehicle to control. [VIN-number] str (required)"
      example: "ABCDE9FG0H1234567"
    temp:
      description: "[16-30] Target climatisation temperature (global)"
      example: "22"
    timers:
      description: "List of timers with settings."
      example: '[{"id": 1,"recurring": ["mon","tue","fri"],"departureTimeOfDay": "08:30","operationCharging": True,"chargeMaxCurrent": "Max","targetChargelevel": 100,"operationClimatisation": True,"heaterSource": "electric","timerProgrammedStatus": "programmed"},{"id":2,"single":"2020-11-30","departureTimeOfDay":"13:30"}]'
    id:
      description: "[1, 2, 3] ID of schedule to set"
    recurring:
      description: "[list: mon-sun] Days for recurring schedule, overrides 'single' option"
    single:
      description: "[YYYY-MM-DD] Date for non recurring schedule, can't be combined with recurring"
    departureTimeOfDay:
      description: "[HH:MM] Time for the schedule"
    operationCharging:
      description: "[true, false] Wether or not charging should occur for schedule"
    chargeMaxCurrent:
      description: "[Max, Reduced] Maximum charge current for schedule"
    targetChargeLevel:
      description: "[1-100] Target % of charge for schedule"
    operationClimatisation:
      description: "[true, false] Wether or not climatisation should occur for schedule"
    heaterSource:
      description: "[automatic, electric] Allow the Use auxillary (requires S-PIN) or only electric heater for climatisation"
    timerProgrammedStatus:
      description: "[programmed, notProgrammed] Activate the schedule or not"
