set_pheater_duration:
  description: "Set duration for parking heater/ventilation"
  fields:
    vin:
      description: "VIN number for vehicle to control. [VIN-number] str (required)"
      example: "ABCDE9FG0H1234567"
    duration:
      description: "[10,20,30,40,50,60] Parking heater duration for heating/ventilation"
      example: '20'
