name: Release

on:
  release:
    types: [prereleased,published]

jobs:
  build:
    name: Upload Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0

      - name: Create zip
        run: |
          cd custom_components/skodaconnect
          zip skodaconnect.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/skodaconnect/skodaconnect.zip
          asset_name: skodaconnect.zip
          tag: ${{ github.ref }}
          overwrite: true